# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_exlist.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExList(object):
    def setupUi(self, ExList):
        ExList.setObjectName("ExList")
        ExList.resize(577, 374)
        self.gridLayout_5 = QtWidgets.QGridLayout(ExList)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_1 = QtWidgets.QLabel(ExList)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout_4.addWidget(self.label_1, 0, 0, 1, 1)
        self.tabWidget_left = QtWidgets.QTabWidget(ExList)
        self.tabWidget_left.setObjectName("tabWidget_left")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView_left_1 = QtWidgets.QListView(self.tab)
        self.listView_left_1.setDragEnabled(True)
        self.listView_left_1.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listView_left_1.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.listView_left_1.setObjectName("listView_left_1")
        self.gridLayout_2.addWidget(self.listView_left_1, 0, 0, 1, 1)
        self.tabWidget_left.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listView_left_2 = QtWidgets.QListView(self.tab_2)
        self.listView_left_2.setObjectName("listView_left_2")
        self.gridLayout_3.addWidget(self.listView_left_2, 0, 0, 1, 1)
        self.tabWidget_left.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget_left, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_all2right = QtWidgets.QPushButton(ExList)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_all2right.setFont(font)
        self.pushButton_all2right.setObjectName("pushButton_all2right")
        self.verticalLayout.addWidget(self.pushButton_all2right)
        self.pushButton_all2left = QtWidgets.QPushButton(ExList)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_all2left.setFont(font)
        self.pushButton_all2left.setObjectName("pushButton_all2left")
        self.verticalLayout.addWidget(self.pushButton_all2left)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(ExList)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget_right = QtWidgets.QTabWidget(ExList)
        self.tabWidget_right.setObjectName("tabWidget_right")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listView_right_1 = QtWidgets.QListView(self.tab_3)
        self.listView_right_1.setDragEnabled(True)
        self.listView_right_1.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listView_right_1.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.listView_right_1.setWordWrap(False)
        self.listView_right_1.setObjectName("listView_right_1")
        self.gridLayout_6.addWidget(self.listView_right_1, 0, 0, 1, 1)
        self.tabWidget_right.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listView_right_2 = QtWidgets.QListView(self.tab_4)
        self.listView_right_2.setObjectName("listView_right_2")
        self.gridLayout_7.addWidget(self.listView_right_2, 0, 0, 1, 1)
        self.tabWidget_right.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget_right, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_confirm = QtWidgets.QPushButton(ExList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_confirm.sizePolicy().hasHeightForWidth())
        self.pushButton_confirm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout.addWidget(self.pushButton_confirm)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 3)

        self.retranslateUi(ExList)
        self.tabWidget_left.setCurrentIndex(0)
        self.tabWidget_right.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ExList)

    def retranslateUi(self, ExList):
        _translate = QtCore.QCoreApplication.translate
        ExList.setWindowTitle(_translate("ExList", "Form"))
        self.label_1.setText(_translate("ExList", "全部项目"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.tab), _translate("ExList", "Frame 1"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.tab_2), _translate("ExList", "Frame 2"))
        self.pushButton_all2right.setToolTip(_translate("ExList", "全部移至右边"))
        self.pushButton_all2right.setText(_translate("ExList", ">>>"))
        self.pushButton_all2left.setToolTip(_translate("ExList", "全部移至左边"))
        self.pushButton_all2left.setText(_translate("ExList", "<<<"))
        self.label_2.setText(_translate("ExList", "导出项目"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.tab_3), _translate("ExList", "Frame 1"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.tab_4), _translate("ExList", "Frame 2"))
        self.pushButton_confirm.setText(_translate("ExList", "确认导出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExList = QtWidgets.QWidget()
    ui = Ui_ExList()
    ui.setupUi(ExList)
    ExList.show()
    sys.exit(app.exec_())
