# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_serial.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialDebugger(object):
    def setupUi(self, SerialDebugger):
        SerialDebugger.setObjectName("SerialDebugger")
        SerialDebugger.resize(760, 608)
        self.gridLayout = QtWidgets.QGridLayout(SerialDebugger)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(SerialDebugger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit_rx = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_rx.setUndoRedoEnabled(False)
        self.plainTextEdit_rx.setReadOnly(True)
        self.plainTextEdit_rx.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit_rx.setObjectName("plainTextEdit_rx")
        self.verticalLayout_4.addWidget(self.plainTextEdit_rx)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(SerialDebugger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit_tx = QtWidgets.QPlainTextEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_tx.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_tx.setSizePolicy(sizePolicy)
        self.plainTextEdit_tx.setObjectName("plainTextEdit_tx")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_tx)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(SerialDebugger)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_port = QtWidgets.QLabel(self.groupBox)
        self.label_port.setObjectName("label_port")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_port.setEditable(False)
        self.comboBox_port.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.comboBox_port.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_port.setDuplicatesEnabled(False)
        self.comboBox_port.setObjectName("comboBox_port")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_port)
        self.label_baudrate = QtWidgets.QLabel(self.groupBox)
        self.label_baudrate.setObjectName("label_baudrate")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_baudrate)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_baudrate)
        self.label_bytesize = QtWidgets.QLabel(self.groupBox)
        self.label_bytesize.setObjectName("label_bytesize")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_bytesize)
        self.comboBox_bytesize = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_bytesize.setObjectName("comboBox_bytesize")
        self.comboBox_bytesize.addItem("")
        self.comboBox_bytesize.addItem("")
        self.comboBox_bytesize.addItem("")
        self.comboBox_bytesize.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_bytesize)
        self.label_parity = QtWidgets.QLabel(self.groupBox)
        self.label_parity.setObjectName("label_parity")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_parity)
        self.comboBox_parity = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_parity)
        self.label_stopbits = QtWidgets.QLabel(self.groupBox)
        self.label_stopbits.setObjectName("label_stopbits")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_stopbits)
        self.comboBox_stopbits = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_stopbits.setObjectName("comboBox_stopbits")
        self.comboBox_stopbits.addItem("")
        self.comboBox_stopbits.addItem("")
        self.comboBox_stopbits.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_stopbits)
        self.label_port_state = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_port_state.setFont(font)
        self.label_port_state.setLineWidth(1)
        self.label_port_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_port_state.setObjectName("label_port_state")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.label_port_state)
        self.pushButton_port_onoff = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_port_onoff.setObjectName("pushButton_port_onoff")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.pushButton_port_onoff)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(SerialDebugger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_hex_show = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_hex_show.setChecked(False)
        self.checkBox_hex_show.setTristate(False)
        self.checkBox_hex_show.setObjectName("checkBox_hex_show")
        self.gridLayout_2.addWidget(self.checkBox_hex_show, 0, 0, 1, 1)
        self.pushButton_rx_clear = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_rx_clear.setObjectName("pushButton_rx_clear")
        self.gridLayout_2.addWidget(self.pushButton_rx_clear, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.groupBox_5 = QtWidgets.QGroupBox(SerialDebugger)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_send = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout_3.addWidget(self.pushButton_send, 0, 0, 1, 1)
        self.checkBox_timer_en = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_timer_en.setObjectName("checkBox_timer_en")
        self.gridLayout_3.addWidget(self.checkBox_timer_en, 4, 0, 1, 1)
        self.checkBox_hex_send = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_hex_send.setObjectName("checkBox_hex_send")
        self.gridLayout_3.addWidget(self.checkBox_hex_send, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 6, 1)
        self.pushButton_tx_clear = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_tx_clear.setObjectName("pushButton_tx_clear")
        self.gridLayout_3.addWidget(self.pushButton_tx_clear, 1, 0, 1, 1)
        self.checkBox_newline = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_newline.setToolTip("")
        self.checkBox_newline.setObjectName("checkBox_newline")
        self.gridLayout_3.addWidget(self.checkBox_newline, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_timer = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_timer.setToolTip("")
        self.lineEdit_timer.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_timer.setObjectName("lineEdit_timer")
        self.horizontalLayout_3.addWidget(self.lineEdit_timer)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(3, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(SerialDebugger)
        QtCore.QMetaObject.connectSlotsByName(SerialDebugger)

    def retranslateUi(self, SerialDebugger):
        _translate = QtCore.QCoreApplication.translate
        SerialDebugger.setWindowTitle(_translate("SerialDebugger", "Form"))
        self.groupBox_2.setTitle(_translate("SerialDebugger", "接收区"))
        self.groupBox_3.setTitle(_translate("SerialDebugger", "发送区"))
        self.groupBox.setTitle(_translate("SerialDebugger", "串口配置"))
        self.label_port.setText(_translate("SerialDebugger", "串口"))
        self.label_baudrate.setText(_translate("SerialDebugger", "波特率"))
        self.comboBox_baudrate.setItemText(0, _translate("SerialDebugger", "115200"))
        self.comboBox_baudrate.setItemText(1, _translate("SerialDebugger", "2400"))
        self.comboBox_baudrate.setItemText(2, _translate("SerialDebugger", "4800"))
        self.comboBox_baudrate.setItemText(3, _translate("SerialDebugger", "9600"))
        self.comboBox_baudrate.setItemText(4, _translate("SerialDebugger", "14400"))
        self.comboBox_baudrate.setItemText(5, _translate("SerialDebugger", "19200"))
        self.comboBox_baudrate.setItemText(6, _translate("SerialDebugger", "38400"))
        self.comboBox_baudrate.setItemText(7, _translate("SerialDebugger", "57600"))
        self.comboBox_baudrate.setItemText(8, _translate("SerialDebugger", "76800"))
        self.comboBox_baudrate.setItemText(9, _translate("SerialDebugger", "128000"))
        self.comboBox_baudrate.setItemText(10, _translate("SerialDebugger", "230400"))
        self.comboBox_baudrate.setItemText(11, _translate("SerialDebugger", "460800"))
        self.comboBox_baudrate.setItemText(12, _translate("SerialDebugger", "921600"))
        self.comboBox_baudrate.setItemText(13, _translate("SerialDebugger", "自定义"))
        self.label_bytesize.setText(_translate("SerialDebugger", "数据位"))
        self.comboBox_bytesize.setItemText(0, _translate("SerialDebugger", "8"))
        self.comboBox_bytesize.setItemText(1, _translate("SerialDebugger", "7"))
        self.comboBox_bytesize.setItemText(2, _translate("SerialDebugger", "6"))
        self.comboBox_bytesize.setItemText(3, _translate("SerialDebugger", "5"))
        self.label_parity.setText(_translate("SerialDebugger", "校验位"))
        self.comboBox_parity.setItemText(0, _translate("SerialDebugger", "无"))
        self.comboBox_parity.setItemText(1, _translate("SerialDebugger", "奇校验"))
        self.comboBox_parity.setItemText(2, _translate("SerialDebugger", "偶校验"))
        self.label_stopbits.setText(_translate("SerialDebugger", "停止位"))
        self.comboBox_stopbits.setItemText(0, _translate("SerialDebugger", "1"))
        self.comboBox_stopbits.setItemText(1, _translate("SerialDebugger", "1.5"))
        self.comboBox_stopbits.setItemText(2, _translate("SerialDebugger", "2"))
        self.label_port_state.setText(_translate("SerialDebugger", "串口已关闭"))
        self.pushButton_port_onoff.setText(_translate("SerialDebugger", "打开串口"))
        self.groupBox_4.setTitle(_translate("SerialDebugger", "接收设置"))
        self.checkBox_hex_show.setText(_translate("SerialDebugger", "16进制显示"))
        self.pushButton_rx_clear.setText(_translate("SerialDebugger", "清空接收区"))
        self.groupBox_5.setTitle(_translate("SerialDebugger", "发送设置"))
        self.pushButton_send.setToolTip(_translate("SerialDebugger", "Ctrl+Enter"))
        self.pushButton_send.setText(_translate("SerialDebugger", "发送"))
        self.pushButton_send.setShortcut(_translate("SerialDebugger", "Ctrl+Return"))
        self.checkBox_timer_en.setText(_translate("SerialDebugger", "定时发送"))
        self.checkBox_hex_send.setText(_translate("SerialDebugger", "16进制发送"))
        self.pushButton_tx_clear.setText(_translate("SerialDebugger", "清除"))
        self.checkBox_newline.setText(_translate("SerialDebugger", "发送新行"))
        self.label_9.setText(_translate("SerialDebugger", " ms/次"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SerialDebugger = QtWidgets.QWidget()
    ui = Ui_SerialDebugger()
    ui.setupUi(SerialDebugger)
    SerialDebugger.show()
    sys.exit(app.exec_())
